### ISSUE TITLE
mouse cursor peg saved with share image

### ISSUE THREAD

**Issue by TheHexCoder0x10** [adamdalechurch/brite-lite-full-stack#2]
the peg that shows where your mouse cursor is shows up when you share the image on that image that is shared. it ideally would be removed from there but you might see it fine as is its just a suggestion

**Comment by adamdalechurch** [comment]
Thank you for submitting this issue.

Resolved with the following commit:

https://github.com/adamdalechurch/brite-lite-full-stack/commit/c75516f251c5f02aa1753c50f6ec01e6374968f7

👍

**Comment by adamdalechurch** [comment]
Thank you for submitting this issue.

Resolved with the following commit:

https://github.com/adamdalechurch/brite-lite-full-stack/commit/c75516f251c5f02aa1753c50f6ec01e6374968f7

👍
